<style>
    div#l1{
        display: flex;
        flex-direction: row;
        padding: 20px;
    }
</style>
<div id="l1" class="verde">
    <Button>
        <a href="/app/view/gestor/registar-funcionario/pesquisar-funcionario.php">
        Registar<br>
        Funcionários
        </a>
    </Button>
    <Button>
        Registar<br>
        Rotas
    </Button>
</div>
<div id="l2" class="verde">
    <Button>
        Registar<br>
        Autocarros
    </Button>
    <Button id="verde-escuro">
        Consultar<br>
        Autocarros
    </Button>
</div>