<link rel="stylesheet" href="/css/login-form-style.css">
<div class="form">
    <form action = "/autenticar" method="post">
        <fieldset>
            <label for="">LOG IN</label>
                <p>
                    <input type="tel" name="telefone" id="id_usuario" placeholder="Telefone">
                </p>
                <p>
                    <input type="password" name="senha" id="senha_usuario" placeholder="Senha">
                </p>
                <p id="btn-submit">
                    <input type="submit" value="Entrar">
                </p>
            </fieldset>
    </form>
</div>