<link rel="stylesheet" href="/css/login-form-style.css">
<div class="form">
    <form action = "../../app/controller/LoginController.php" method="post">
        <fieldset>
            <label for="">LOG IN</label>
                <p>
                    <input type="tel" name="id_usuario" id="id_usario" placeholder="Telefone">
                </p>
                <p>
                    <input type="password" name="senha_usuario" id="senha_usuario" placeholder="Senha">
                </p>
                <p id="btn-submit">
                    <input type="submit" value="Entrar">
                </p>
            </fieldset>
    </form>
</div>