<h2 class="titulo">Registar Funcionario</h2>
<div class="linha1">
    <div class="sublinha">
        <div>
            <label for="">Nome</label>
            <input type="text" name="nome" required id="">
        </div>
        <div>
            <label for="">Apelido</label>
            <input type="text" name="apelido" required id="">
        </div>
        <div>
            <label for="">sexo</label>
            <select name="sexo" id="">
                <option value="m" selected>M</option>
                <option value="f">F</option>
            </select>
        </div>
        <div>
            <label for="">Data de Nascimento</label>
            <input type="date" name="dtNascimento" id="">
        </div>
    </div>
    <div class="sublinha">
        <div>
            <label for="documento">DOCUMENTO</label> 
            <select name="documento" id="documento">
                <option value="BI">BI</option>
                <option value="Cartao de eleitor">Cartao de Eleitor</option>
                <option value="DIRE">DIRE</option>
                <option value="Passaporte">Passaporte</option>
            </select>
        </div>
        <div>
            <label for="">Numero</label>
            <input type="text" name="numeroDocumento" id="">
        </div>
    </div>
    <div class="sublinha">
       <div>
            <label for="">NUIT</label>
            <input type="number" name="nuit" id="">
       </div>
       <div>
            <label for="">Funcao</label>
            <select name="funcao" id="">
                <option value="1">gestor</option>
                <option value="2">secretaria</option>
                <option value="3">fiscal</option>
                <option value="4">motorista</option>
                <option value="5">cobrador</option>
            </select>
        </div>
        <div>
            <label for="">Telefone</label>
            <input type="tel" name="telefone" id="">
        </div>
    </div>
    <div class="sublinha">
       <div>
            <label for="">Numero de Carta</label>
            <input type="number" name="numerocarta" id="">
       </div>
       <div>
            <label for="">Categoria</label>
            <select name="categoriaCarta" id="">
                <option value="pesado">Pesado</option>
                <option value="ligeiro">ligeiro</option>
                <option value="profisisonal" selected>Profissional</option>
            </select>
        </div>
        <div>
            <label for="">Nivel Academico</label>
            <select name="categoriaCarta" id="">
                <option value="basico" selected>Basico</option>
                <option value="medio">Medio</option>
                <option value="superior" >Superior</option>
            </select>
        </div>
        <div>
            <label for="">Formacao</label>
            <input type="tel" name="formacaoAcademica" id="">
        </div>
    </div>
    

</div>
<div class="linha2">
   <fieldset>
       <p id="destaque">RESIDÊCIA</p>
       <div class="sublinha">
            <div>
                <label for="">PROVINCIA</label>
                <input type="text" name="provincia" id="">
            </div>
            <div>
                <label for="">DISTRITO</label>
                <input type="text" name="distrito" id="">
            </div>
            <div>
                <label for="">BAIRRO</label>
                <input type="text" name="bairro" id="">
            </div>
        </div>
        <div class="sublinha">
            <div>
                <label for="">QUARTEIRAO</label>
                <input type="number" name="quarteirap" id="">
                <label for="">CASA Nº</label>
                <input type="number" name="casa" id="">
            </div>
        </div>
   </fieldset>
</div>