<style>
    .titulo{
        display: grid;
        place-items: center;
        background-color: #00C076;
        width:50vw;
    }
    body .corpo{
        display: grid;
        place-items: center;
    }
    .corpo{
        margin-top: 50px;
    }
    .titulo{
        margin: 10px 0px;
        width: 300px;
        margin-top: 0px;
    }
    .caixa{
        border: solid #00C076 1px;
        height: 300px;
    }
    .ok{
        display: grid;
        place-items: center;
    }
    img{
        width: 150px;
        height: auto;
        
    }
</style>
<div class="corpo">
    <div class="caixa">
        <header class="titulo">REGISTADO</header>
        <a href="/pesquisarFuncionario">
            <div class="ok">
                <img src="/img/ok-grande.png" alt="" srcset="">
            </div>
        </a>
    </div>
</div>