<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <!--Para o Header-->
    <link rel="stylesheet" href="/css/layout-template-styles/dashboard.css">
</head>
<body>
    
    <div class="corpo">
        <div id="esquerda">
            <header>Sistema de Gest&atilde;o de Funcion&aacute;rios e Autocarro</header>
            <div class="menu">
                <h2>Menu Principal</h2>
                <div class="btn">
                <?= $this->content() ?>
                </div>
            </div>
            <footer>SGFAT &#64; 2021</footer>
        </div>
        <div id="direita">

            <div class="info">
                <p>
                    <img src="/img/user-64.png" alt="user-64" srcset="">
                </p>
                <div id="info">
                <div>
                        Funcao:
                        <div>
                            <?= strtoupper($_SESSION['funcao']);?>
                        </div>
                    </div>
                    <div>
                        Nome:
                        <div>
                            <?= strtoupper($_SESSION['nome']);?>
                        </div>
                    </div>
                    <div>
                        Telefone:
                        <div>
                            <?=  strtoupper($_SESSION['telefone']);?>
                        </div>
                    </div>   
                </div>
            </div>
            <a href="/terminarSessao" class="logout">TERMINAR SESSAO</a>
        </div>
       
    </div>
</body>
</html>