<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <!--Para o Header-->
    <link rel="stylesheet" href="/css/header-style.css">
</head>
<body>
    
    <div class="corpo">
        <header>Sistema de Gest&atilde;o de Funcion&aacute;rios e Autocarro</header>
        <div class="menu">
            <?= $this->content() ?>
            <footer>SGFAT &#64; 2021</footer>
        </div>
        <div class="info">
            <p>
                <img src="/img/user-64.png" alt="user-64" srcset="">
            </p>
            <p id="info">
                Aqui Fica a descricao Responsabilidade do model
            </p>
        </div>
    </div>
</body>
</html>