<html>
	<head>
		<meta charset="utf-8" />
		<title>SGFAT</title>
		<!--Header-->
		<link rel="stylesheet" href="/css/layout-style.css">
	</head>

	<body>
		<header>Sistema de Gest&atilde;o de Funcion&aacute;rios e Autocarro</header>
		<div>
			<?= $this->content() ?>
		</div>
		<a href="/dashboard/<?=$_SESSION['funcao'] ?>">
			<button class="cancelar">CANCELAR</button>
		</a>
		<footer>SGFAT &#64; 2021</footer>
	</body>

</html>