<html>
	<head>
		<meta charset="utf-8" />
		<title>Registar</title>
		<!--Header-->
		<link rel="stylesheet" href="/css/layout-template-styles/registarLayout.css">
	</head>

	<body>
	
    <form action="/continuarRegisto" method="post">
        <?= $this->content() ?>
        <input type="submit" id="submeter" value="Continuar">
        <input type="button" id = "cancelar" value="Cancelar">
    </form>
		

	</body>

</html>